services:
  user-ms:
    image: user-ms
    ports:
      - 8080:8080
    links:
      - mongo-server
    networks:
      - three-tier-network
  
  order-ms:
    image: order-ms
    ports:
      - 3000:3000
    links:
      - mysql
    networks:
      - three-tier-network
    
  react-frontend:
    image: react-frontend
    ports:
      - 3001:3001
    links:
      - order-ms
    networks:
      - three-tier-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-server
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: q
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
    links:
      - mongo-server
    networks:
      - three-tier-network

  mongo-server:
    image: mongo:latest
    container_name: mongo-server
    environment:
      MONGO_INITDB_DATABASE: demodb  
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - three-tier-network
  
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: redhat1234#
    ports:
      - "3307:3306"
    networks:
      - three-tier-network

networks: 
    three-tier-network:
      driver: bridge

volumes:
  mongodb_data_container: