CREATE DATABASE IF NOT EXISTS Three_Tier_Project;

USE Three_Tier_Project;

CREATE TABLE IF NOT EXISTS Orders (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `Customer_ID` VARCHAR(255) NOT NULL UNIQUE,
  `Price` DECIMAL(10, 2) NOT NULL
);